### PR TITLE
Implement metals/didFocusTextDocument notification

### PR DESCRIPTION
**Pull request by ayoub-benali**
Send [metals/didFocusTextDocument](https://scalameta.org/metals/docs/integrations/new-editor.html#metalsdidfocustextdocument) on view focus.

All credit goes to @rwols for making this feature work.

### CODE REVIEW

**Review by ckipp01 — APPROVED** [review]
😬 A bit hard to review without knowing much about the Submarine internals, but this looks good to me

**Review by tgodzik — APPROVED** [review]
LGTM! As far as I can tell :sweat_smile:  :motor_boat:

**Comment by tgodzik** [comment]
> Submarine

Was that indented? :laughing:

**Comment by ckipp01** [comment]
> > Submarine
> 
> Was that indented? 😆

..... autocorrect. Awesome.

**Pull request merged**
