### PR TITLE
Use public imports and adapt to new LSP version

### PR DESCRIPTION
**Pull request by rchl**
- Switch to importing from public LSP exports, where available. Otherwise things can potentially break in the future.
- Adapted to latest version of LSP (not released yet at the time of writing) where the `Range` class was removed.
- Some minor linting fixes (I'm running flake8 locally)

Those changes can be released at any point after the next version of LSP is released.

### CODE REVIEW

**Review by ayoub-benali — APPROVED** [review]

**Comment by ayoub-benali** [comment]
Thanks @rchl ! just ping me when LSP is released

**Comment by rchl** [comment]
We're planning to release LSP today or tomorrow. What time are you available @ayoub-benali to do a synchronized release?

**Comment by predragnikolic** [comment]
Hello @ayoub-benali,
Could you give merge + release rights to @rchl or me? 

That way we could easily migrate this new change of lsp.

It would be great if we did the migration on the weekend(probably this weekend, if nothing prevents us from doing that) when nobody is working 🙂

**Comment by ayoub-benali** [comment]
Hi, I granted your and @rchl more permission you should be able to make a release. 
I can also merge and release this PR this weekend.

**Comment by predragnikolic** [comment]
Thanks @ayoub-benali :+1: 
I will probably just prepare a draft release, 
once the LSP is published, we can just release the draft release.

**Pull request merged**
